### PR TITLE
Remove unused patch for libandroidfw

### PR DESCRIPTION
**Pull request by eli-schwartz**
The patch is unused now that the submodule is unused. I was a couple minutes too slow amending the previous PR include this deletion.

### CODE REVIEW

**Comment by anatol** [comment]
Thank you for the github CI fix!

**Comment by eli-schwartz** [comment]
It's a problem I've fought before. :) Github unfortunately does not consider it worthwhile to design their runners correctly such that brew install is able to update the files it installed...

**Comment by anatol** [comment]
> It's a problem I've fought before. :) Github unfortunately does not consider it worthwhile to design their runners correctly such that brew install is able to update the files it installed...

Interesting, what is their reasoning for doing such a controversial decision?

**Comment by eli-schwartz** [comment]
https://github.com/orgs/Homebrew/discussions/3895#discussioncomment-4130560
https://github.com/actions/setup-python/issues/577

I think it has more or less died the death of "no one is motivated to look at the issue". The primary way it manifests, anyway, is that whenever python is updated in homebrew then brew errors out, but most of the year brew doesn't try to touch the python installation, and so, doesn't notice it's broken. So by the time anyone gets around to looking at the problem, it's not a problem anymore? :D   

And then the problem comes back again, regularly...

**Pull request merged**
