### PR TITLE
Upgrade to platform-tools-35.0.1

### PR DESCRIPTION
**Pull request by Biswa96**

### CODE REVIEW

**Comment by Biswa96** [comment]
I do not know how to troubleshoot the compiler error in Fedora.

**Comment by Biswa96** [comment]
I do not know how to troubleshoot the compiler error in Fedora.

**Comment by munix9** [comment]
I can reproduce the error in openSUSE Tumbleweed with gcc 14.

With the following patch the build works with clang, gcc 13 and gcc 14, but I'm not sure if this is the clean way to do it:
```
--- a/vendor/boringssl/crypto/internal.h
+++ b/vendor/boringssl/crypto/internal.h
@@ -1144,7 +1144,7 @@ static inline uint64_t CRYPTO_rotr_u64(u
 
 // CRYPTO_addc_* returns |x + y + carry|, and sets |*out_carry| to the carry
 // bit. |carry| must be zero or one.
-#if OPENSSL_HAS_BUILTIN(__builtin_addc)
+#if OPENSSL_HAS_BUILTIN(__builtin_addc) && (!defined(__GNUC__) || (defined(__GNUC__) && (__GNUC__ < 14)))
 
 #define CRYPTO_GENERIC_ADDC(x, y, carry, out_carry) \
   (_Generic((x),                                    \
@@ -1196,7 +1196,7 @@ static inline uint64_t CRYPTO_addc_u64(u
 
 // CRYPTO_subc_* returns |x - y - borrow|, and sets |*out_borrow| to the borrow
 // bit. |borrow| must be zero or one.
-#if OPENSSL_HAS_BUILTIN(__builtin_subc)
+#if OPENSSL_HAS_BUILTIN(__builtin_subc) && (!defined(__GNUC__) || (defined(__GNUC__) && (__GNUC__ < 14)))
 
 #define CRYPTO_GENERIC_SUBC(x, y, borrow, out_borrow) \
   (_Generic((x),                                      \
```

**Comment by Biswa96** [comment]
That seems more like workaround. Is gcc 14 released yet?

**Comment by munix9** [comment]
Yes of course, that would be a workaround.
Fedora apparently already uses gcc 14 by default.
openSUSE Tumbleweed already offers gcc 14, but gcc 13 is currently still the default.

Another possibility would be to adapt the checks for fedora so that gcc 13 is used (if it is offered).

**Comment by Biswa96** [comment]
I have added the above workaround for gcc 14. Waiting for reviews...

**Comment by munix9** [comment]
That is correct. The problem is known and a solution is being worked on. It has probably already been fixed for the next version Leap 15.6, but unfortunately not yet for the current "latest" version, i.e. Leap 15.5.

**Comment by anatol** [comment]
It is great to hear. @munix9 do you have a link to the upstream discussion to learn more about the root of the problem and proposed solution?

**Comment by munix9** [comment]
The basic problem is probably that Leap also uses binary packages from the SUSE distribution (the commercial one with support).
There protobuf is linked with libabsl 2308.0.0, but other packages only in Leap are linked with libabsl 2401.0.0.
This leads to conflicts with some other packages.
This must now be resolved.

https://github.com/nmeum/android-tools/issues/143
https://bugzilla.opensuse.org/show_bug.cgi?id=1222343

**Comment by anatol** [comment]
As the opensuse bot issue is identified as the upstream one I am +1 with merging this PR into `master`. Opensuse will catch up and the buildbot will be eventually fixed.

**Comment by anatol** [comment]
`master` looks good to me. It is time for a new `35.0.1` release!

**Comment by Biswa96** [comment]
> I'm having issues with this 35.0.1 version, on NixOS.

Does the issue happen with 35.0.2? It has an option to use system libusb or the bundled one. Please try with it being enabled and disabled.

**Comment by s1341** [comment]
I tested the android-tools 35.0.2 from the pending PR https://github.com/NixOS/nixpkgs/pull/382382, and observed the same behavior.

It seems that PR uses the bundled libusb. I don't think I can easily test with the system libusb, as if I understand correctly, android-tools uses libusb functionality not yet released in upstream libusb?

In any event, something is off here...

**Pull request merged**
