### PR TITLE
Add e2fsdroid and ext2simg

### PR DESCRIPTION
**Pull request by munix9**

### CODE REVIEW

**Comment by mid-kid** [comment]
Why was this closed?

**Comment by munix9** [comment]
Sent to nirvana.
I should not share my accounts with a cat ...
I'll create a new PR later also for the python tools with some additional comments.

**Comment by munix9** [comment]
looks like `vendor/e2fsprogs/contrib/android/e2fsdroid.c` needs an `#include <sys/types.h>` for musl environments.

**Comment by Johnnynator** [comment]
I rebased your branch and blindly added `target_compile_definitions(e2fsdroid PUBLIC HAVE_SYS_TYPES_H)` for now.

**Pull request merged**
