### PR TITLE
Upgrade to platform-tools-34.0.0

### PR DESCRIPTION
**Pull request by Biswa96**

### CODE REVIEW

**Review by nmeum — APPROVED** [review]
LGTM! Thanks for your work on this.

**Comment by anatol** [comment]
LGTM!

**Comment by anatol** [comment]
@nmeum what do you think about a new project release?

**Comment by nmeum** [comment]
> @nmeum what do you think about a new project release?

Sounds like a good idea. I would suggest waiting a few days to see if any issues show up (I am currently using/testing Git HEAD with my setup) and then tagging a new release.

**Pull request merged**
